#!/usr/bin/env python3
"""
generate_opml.py -- build feeds/subscriptions.opml from:
  1. Scrapers registered in scrapers/__init__.py  (auto-generated feeds in this repo)
  2. Manual entries in subscriptions.yml          (feeds you've found elsewhere)

Usage:
    python generate_opml.py
"""

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml")

from scrapers import ALL_SCRAPERS

REPO_ROOT = Path(__file__).parent
FEEDS_DIR = REPO_ROOT / "feeds"
SUBS_FILE = REPO_ROOT / "subscriptions.yml"
OUT_FILE  = FEEDS_DIR / "subscriptions.opml"


def _esc(s: str) -> str:
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;")
             .replace('"', "&quot;"))


def _feed_url(slug: str) -> str:
    repo = os.environ.get("GITHUB_REPOSITORY", "YOUR_GITHUB_USERNAME/atom-feeds")
    return f"https://raw.githubusercontent.com/{repo}/main/feeds/{slug}.atom"


def _outline(text: str, title: str, xml_url: str, html_url: str = "") -> str:
    attrs = f'type="rss" text="{_esc(text)}" title="{_esc(title)}" xmlUrl="{_esc(xml_url)}"'
    if html_url:
        attrs += f' htmlUrl="{_esc(html_url)}"'
    return f'      <outline {attrs}/>'


def build_opml(scrapers, manual_feeds: list) -> str:
    updated = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S GMT")
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<opml version="2.0">',
        '  <head>',
        '    <title>atom-feeds subscriptions</title>',
        f'    <dateModified>{updated}</dateModified>',
        '  </head>',
        '  <body>',
        '',
        '    <!-- Feeds generated by scrapers in this repository -->',
        '    <outline text="Generated Feeds" title="Generated Feeds">',
    ]
    for scraper in scrapers:
        lines.append(_outline(
            text=scraper.FEED_TITLE,
            title=scraper.FEED_TITLE,
            xml_url=_feed_url(scraper.FEED_SLUG),
            html_url=scraper.SOURCE_URL,
        ))
    lines.append('    </outline>')

    # Group manual feeds by category
    by_category: dict[str, list] = {}
    for feed in manual_feeds:
        cat = (feed.get("category") or "Uncategorized").strip()
        by_category.setdefault(cat, []).append(feed)

    if by_category:
        lines.append('')
        lines.append('    <!-- Manually curated subscriptions -->')
        for category in sorted(by_category):
            lines.append(f'    <outline text="{_esc(category)}" title="{_esc(category)}">')
            for feed in by_category[category]:
                lines.append(_outline(
                    text=feed.get("title") or feed["url"],
                    title=feed.get("title") or feed["url"],
                    xml_url=feed["url"],
                    html_url=feed.get("site_url", ""),
                ))
            lines.append('    </outline>')

    lines += ['', '  </body>', '</opml>', '']
    return '\n'.join(lines)


def load_subscriptions() -> list:
    if not SUBS_FILE.exists():
        print(f"  {SUBS_FILE.name} not found -- no manual entries")
        return []
    data = yaml.safe_load(SUBS_FILE.read_text(encoding="utf-8")) or {}
    feeds = data.get("feeds") or []
    if not isinstance(feeds, list):
        print(f"  Warning: 'feeds' key in {SUBS_FILE.name} is not a list -- skipping")
        return []
    valid = [f for f in feeds if isinstance(f, dict) and f.get("url")]
    skipped = len(feeds) - len(valid)
    if skipped:
        print(f"  Warning: skipped {skipped} entr{'y' if skipped == 1 else 'ies'} missing a 'url' field")
    return valid


def main():
    print("Loading subscriptions ...")
    manual = load_subscriptions()
    print(f"  {len(manual)} manual subscription(s) from {SUBS_FILE.name}")
    print(f"  {len(ALL_SCRAPERS)} generated feed(s) from scrapers")

    FEEDS_DIR.mkdir(exist_ok=True)
    opml = build_opml(ALL_SCRAPERS, manual)
    OUT_FILE.write_text(opml, encoding="utf-8")
    print(f"Wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
